// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hihnkaxnvjhrjanjqxjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpaG5rYXhudmpocmphbmpxeGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODUwMjUsImV4cCI6MjA2NDA2MTAyNX0.0WVN4_I1Cxb8V5hZZjDdw9n78-gYRoEMUyEhW2QkGiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);